language: go

go:
  - tip
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
script:
  - go test -v -coverprofile=database.coverprofile ./database/
  - go test -v -coverprofile=config.coverprofile ./config/
  - go test -v -coverprofile=web.coverprofile ./web/
  - go test -v -covererofile=main.coverprofile
  - $GOPATH/bin/gover
  - $GOPATH/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci
